LuanVan/Controllers/ChiendichesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LuanVan.Data;

namespace LuanVan.Controllers
{
    public class ChiendichesController : Controller
    {
        private readonly NienluancosoContext _context;

        public ChiendichesController(NienluancosoContext context)
        {
            _context = context;
        }

        // GET: Chiendiches
        public async Task<IActionResult> Index(string? SearchString, DateTime? tu, DateTime? den, string? noiht, int tt =2)
        {
            List<SelectListItem> items = new List<SelectListItem>
{
    new SelectListItem { Value = "1", Text = "Danh sách tất cả chiến dịch" },
    new SelectListItem { Value = "2", Text = "Danh sách chiến dịch đang diễn ra" },
    new SelectListItem { Value = "3", Text = "Danh sách chiến dịch đã kết thúc" }
};
           
            ViewBag.tt = new SelectList(items, "Value", "Text", tt);
            if (tu != null && den != null && SearchString != null && noiht != null)
            {
               var nienluancosoContext2 = _context.Chiendiches.Include(c => c.MaNoiNavigation).Include(c => c.MaTvNavigation).Include(c => c.TtTraotangs).Include(c => c.TtQuyengopHienvats).Where(q => q.Ngaybatdau >= tu && q.Ngayketthuc <= den && q.TenCd.Contains(SearchString) && q.MaNoiNavigation.Diachi.Contains(noiht));

                if (nienluancosoContext2.Count() == 0)
                {
                    ViewBag.tb = "Không tìm thấy chiến dịch có tên: " + SearchString.ToString() + "Từ ngày: " + tu.Value.ToString("dd-MM-yyyy") + " đến: " + den.Value.ToString("dd-MM-yyyy") + " hỗ trợ cho địa chỉ: " + noiht.ToString();
                }
                else
                {
                    ViewBag.tb = "Đã tìm thấy chiến dịch có tên: " + SearchString.ToString() + " Từ ngày:" + tu.Value.ToString("dd-MM-yyyy") + " đến:" + den.Value.ToString("dd-MM-yyyy") + " hỗ trợ cho địa chỉ: " + noiht.ToString();
                }
                return View(await nienluancosoContext2.ToListAsync());
            }
            if (SearchString != null)
            {
                var nienluancosoContext2 = _context.Chiendiches.Include(c => c.MaNoiNavigation).Include(c => c.MaTvNavigation).Include(c => c.TtTraotangs).Include(c => c.TtQuyengopHienvats).Where(c => c.TenCd.Contains(SearchString));
                if (nienluancosoContext2.Count() == 0)
                {
                    ViewBag.tb = "Không tìm thấy chiến dịch có tên : " + SearchString.ToString();
                }
                else
                {
                    ViewBag.tb = "Đã tìm thấy chiến dịch có tên : " + SearchString.ToString();
                }
                return View(await nienluancosoContext2.ToListAsync());
            }
            if (noiht != null)
            {
                var nienluancosoContext2 = _context.Chiendiches.Include(c => c.MaNoiNavigation).Include(c => c.MaTvNavigation).Include(c => c.TtTraotangs).Include(c => c.TtQuyengopHienvats).Where(c => c.MaNoiNavigation.Diachi.Contains(noiht));
                if (nienluancosoContext2.Count() == 0)
                {
                    ViewBag.tb = "Không tìm thấy chiến dịch có địa chỉ nơi hỗ trợ ở: " + noiht.ToString();
                }
                else
                {
                    ViewBag.tb = "Đã tìm thấy chiến dịch có địa chỉ nơi hỗ trợ ở: " + noiht.ToString();
                }
                return View(await nienluancosoContext2.ToListAsync());
            }
            if (tu != null && den != null)
            {
                var nienluancosoContext2 = _context.Chiendiches.Include(c => c.MaNoiNavigation).Include(c => c.MaTvNavigation).Include(c => c.TtTraotangs).Include(c => c.TtQuyengopHienvats).Where(q => q.Ngaybatdau >= tu && q.Ngayketthuc <= den);

                if (nienluancosoContext2.Count() == 0)
                {
                    ViewBag.tb = "Không tìm thấy chiến dịch Từ ngày: " + tu.Value.ToString("dd - MM - yyyy") + " đến: " + den.Value.ToString("dd - MM - yyyy");
                }
                else
                {
                    ViewBag.tb = "Đã tìm thấy chiến dịch Từ ngày: " + tu.Value.ToString("dd - MM - yyyy") + " đến: " + den.Value.ToString("dd - MM - yyyy");
                }
                
                return View(await nienluancosoContext2.ToListAsync());
            }
            if (tt == 1)
            {

                var nienluancosoContext2 = _context.Chiendiches.Include(c => c.MaNoiNavigation).Include(c => c.MaTvNavigation).Include(c => c.TtTraotangs).Include(c => c.TtQuyengopHienvats);

                return View(await nienluancosoContext2.ToListAsync());
            }
            if (tt == 2)
            {
             
                var nienluancosoContext2 = _context.Chiendiches.Include(c => c.MaNoiNavigation).Include(c => c.MaTvNavigation).Include(c => c.TtTraotangs).Include(c => c.TtQuyengopHienvats).Where(q => q.Ngayketthuc > DateTime.Now);

               

                return View(await nienluancosoContext2.ToListAsync());
            }
            if (tt == 3)
            {

                var nienluancosoContext2 = _context.Chiendiches.Include(c => c.MaNoiNavigation).Include(c => c.MaTvNavigation).Include(c => c.TtTraotangs).Include(c => c.TtQuyengopHienvats).Where(q => q.Ngayketthuc < DateTime.Now);

                

                return View(await nienluancosoContext2.ToListAsync());
            }
            var nienluancosoContext = _context.Chiendiches.Include(c => c.MaNoiNavigation).Include(c => c.MaTvNavigation);
            return View(await nienluancosoContext.ToListAsync());
        }

        // GET: Chiendiches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Chiendiches == null)
            {
                return NotFound();
            }

            var chiendich = await _context.Chiendiches
                 .Include(c => c.MaNoiNavigation)
                 .Include(c => c.MaTvNavigation)
                 .Include(c => c.TtQuyengopHienvats)
                 .Include(c => c.TtTraotangs)
                 .FirstOrDefaultAsync(m => m.MaCd == id);
            if (chiendich == null)
            {
                return NotFound();
            }

            return View(chiendich);
        }

        // GET: Chiendiches/Create
        private bool ChiendichExists(int id)
        {
          return (_context.Chiendiches?.Any(e => e.MaCd == id)).GetValueOrDefault();
        }
    }
}

LuanVan/Controllers/TtQuyengopHienvatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LuanVan.Data;
using Microsoft.AspNetCore.Authorization;
using MailKit.Net.Smtp;
using MailKit;
using MimeKit;

namespace LuanVan.Controllers
{
    public class TtQuyengopHienvatsController : Controller
    {
        private readonly NienluancosoContext _context;

        public TtQuyengopHienvatsController(NienluancosoContext context)
        {
            _context = context;
        }

        // GET: TtQuyengopHienvats
        public async Task<IActionResult> Index(string? SearchString, DateTime? tu, DateTime? den, int? tt)
        {
            if (HttpContext.Session.GetInt32("idmtq") != null)
            {
                List<SelectListItem> items = new List<SelectListItem>
{
    new SelectListItem { Value = "1", Text = "Danh sách tất cả quyên góp" },
    new SelectListItem { Value = "2", Text = "Danh sách quyên góp của bản thân" },

};

                ViewBag.tt = new SelectList(items, "Value", "Text", tt);
            }
            if (tu != null && den != null && SearchString != null)
            {
                var nienluancosoContext2 = _context.TtQuyengopHienvats.Include(t => t.MaCdNavigation).Include(t => t.MaHvNavigation).Include(t => t.MaMtqNavigation).Include(t => t.MaTvNavigation).Where(q => q.NgayQg >= tu && q.NgayQg <= den && q.MaMtqNavigation.HotenMtq.Contains(SearchString));

                if (nienluancosoContext2.Count() == 0)
                {
                    ViewBag.tb = "Không tìm thấy quyên góp của: " + SearchString.ToString() + "Từ ngày: " + tu.Value.ToString("dd-MM-yyyy") + "Đến: " + den.Value.ToString("dd-MM-yyyy");
                }
                else
                {
                    ViewBag.tb = "Đã tìm thấy quyên góp của: " + SearchString.ToString() + " Từ ngày:" + tu.Value.ToString("dd-MM-yyyy") + " đến:" + den.Value.ToString("dd-MM-yyyy");
                }
                return View(await nienluancosoContext2.ToListAsync());
            }
            if (SearchString != null)
            {
                var nienluancosoContext2 = _context.TtQuyengopHienvats.Include(t => t.MaCdNavigation).Include(t => t.MaHvNavigation).Include(t => t.MaMtqNavigation).Include(t => t.MaTvNavigation).Where(q => q.MaMtqNavigation.HotenMtq.Contains(SearchString));
                if (nienluancosoContext2.Count() == 0)
                {
                    ViewBag.tb = "Không tìm thấy quyên góp của: " + SearchString.ToString();
                }
                else
                {
                    ViewBag.tb = "Đã tìm thấy quyên góp của: " + SearchString.ToString();
                }
                return View(await nienluancosoContext2.ToListAsync());
            }
            if (tu != null && den != null)
            {
                var nienluancosoContext2 = _context.TtQuyengopHienvats.Include(t => t.MaCdNavigation).Include(t => t.MaHvNavigation).Include(t => t.MaMtqNavigation).Include(t => t.MaTvNavigation).Where(q => q.NgayQg >= tu && q.NgayQg <= den);

                ViewBag.TuNgay = tu.Value.ToString("dd-MM-yyyy");
                ViewBag.DenNgay = den.Value.ToString("dd-MM-yyyy");
                return View(await nienluancosoContext2.ToListAsync());
            }
            if (tt == 1)
            {

                var nienluancosoContext2 = _context.TtQuyengopHienvats.Include(t => t.MaCdNavigation).Include(t => t.MaHvNavigation).Include(t => t.MaMtqNavigation).Include(t => t.MaTvNavigation);

                return View(await nienluancosoContext2.ToListAsync());
            }
            if (tt == 2)
            {

                var nienluancosoContext2 = _context.TtQuyengopHienvats.Include(t => t.MaCdNavigation).Include(t => t.MaHvNavigation).Include(t => t.MaMtqNavigation).Include(t => t.MaTvNavigation).Where(t => t.MaMtq == HttpContext.Session.GetInt32("idmtq"));



                return View(await nienluancosoContext2.ToListAsync());
            }
            var nienluancosoContext = _context.TtQuyengopHienvats.Include(t => t.MaCdNavigation).Include(t => t.MaHvNavigation).Include(t => t.MaMtqNavigation).Include(t => t.MaTvNavigation);
            return View(await nienluancosoContext.ToListAsync());
        }

        // GET: TtQuyengopHienvats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TtQuyengopHienvats == null)
            {
                return NotFound();
            }

            var ttQuyengopHienvat = await _context.TtQuyengopHienvats
                .Include(t => t.MaCdNavigation)
                .Include(t => t.MaHvNavigation)
                .Include(t => t.MaMtqNavigation)
                .Include(t => t.MaTvNavigation)
                .FirstOrDefaultAsync(m => m.MaQghv == id);
            if (ttQuyengopHienvat == null)
            {
                return NotFound();
            }

            return View(ttQuyengopHienvat);
        }

        // GET: TtQuyengopHienvats/Create

        public IActionResult Create(int id)
        {
            if (HttpContext.Session.GetInt32("idmtq") == null)
                return RedirectToAction("Register", "User");
            else if (id != null)
            {
                ViewData["MaHv"] = new SelectList(_context.HienVats, "MaHv", "TenHv");


                ViewData["MaCd"] = new SelectList(_context.Chiendiches.Where(s => s.MaCd == id), "MaCd", "TenCd");
                ViewData["MaMtq"] = new SelectList(_context.Manhthuongquans.Where(s => s.MaMtq == HttpContext.Session.GetInt32("idmtq")), "MaMtq", "HotenMtq");

                return View();
            }


            return NotFound();
        }

        // POST: TtQuyengopHienvats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaQghv,MaHv,MaMtq,MaCd,Ghichu,SoluongQg,TrangthaiHv,NgayQg")] TtQuyengopHienvat ttQuyengopHienvat)
        {

            if (ttQuyengopHienvat.SoluongQg <= 0)
            {
                ModelState.AddModelError("SoluongQg", "Vui lòng điền số lượng ?");
                ViewData["MaHv"] = new SelectList(_context.HienVats, "MaHv", "TenHv");


                ViewData["MaCd"] = new SelectList(_context.Chiendiches.Where(s => s.MaCd == ttQuyengopHienvat.MaCd), "MaCd", "TenCd");
                ViewData["MaMtq"] = new SelectList(_context.Manhthuongquans.Where(s => s.MaMtq == HttpContext.Session.GetInt32("idmtq")), "MaMtq", "HotenMtq");
                return View(ttQuyengopHienvat);


            }
            if (ttQuyengopHienvat.Ghichu == null)
            {
                ModelState.AddModelError("Ghichu", "Hãy viết gì đó cho chúng tôi");
                ViewData["MaHv"] = new SelectList(_context.HienVats, "MaHv", "TenHv");


                ViewData["MaCd"] = new SelectList(_context.Chiendiches.Where(s => s.MaCd == ttQuyengopHienvat.MaCd), "MaCd", "TenCd");
                ViewData["MaMtq"] = new SelectList(_context.Manhthuongquans.Where(s => s.MaMtq == HttpContext.Session.GetInt32("idmtq")), "MaMtq", "HotenMtq");
                return View(ttQuyengopHienvat);


            }
            ttQuyengopHienvat.NgayQg = DateTime.Now;
            ttQuyengopHienvat.TrangthaiHv = "Chưa nhận";
            Manhthuongquan mtq = _context.Manhthuongquans.AsNoTracking().FirstOrDefault(n => n.MaMtq.Equals(HttpContext.Session.GetInt32("idmtq")));
            //send mail



            _context.Add(ttQuyengopHienvat);
            await _context.SaveChangesAsync();
            return RedirectToAction("CamOn", new
            {
                id = ttQuyengopHienvat.MaQghv
            });
        }

        public async Task<IActionResult> CamOn(int id)
        {
            var ttqg = _context.TtQuyengopHienvats.Include(r => r.MaCdNavigation).Include(r => r.MaMtqNavigation).Include(r => r.MaHvNavigation).FirstOrDefault(s => s.MaQghv == id);
            if (ttqg.MaMtqNavigation.EmailMtq != null)
            {
                var message = new MimeMessage();
                message.From.Add(new MailboxAddress("Thiện Nguyện Online", "ThienNguyenOnline@gmail.com"));
                message.To.Add(new MailboxAddress("Mạnh thường quân", ttqg.MaMtqNavigation.EmailMtq));
                message.Subject = "Thư cảm ơn đăng ký quyên góp";
                message.Body = new TextPart("plain")
                {
                    Text = $"Cảm ơn bạn đã quyên góp\n" +
      
       $"Xin hãy gửi kèm MÃ QUYÊN GÓP HIỆN VẬT: \"{ttqg.MaQghv}\" này cho chúng tôi\n" +
      
       $"Mã quyên góp hiện vật: " +
       $"{ttqg.MaQghv}\n" +
       
       $"Mạnh thường quân: " +
      
       $"{ttqg.MaMtqNavigation.HotenMtq}\n" +
       $"Chiến dịch: " +
       $"{ttqg.MaCdNavigation.TenCd} \n" +
       
       $"Hiện vật: " +
      
       $"{ttqg.MaHvNavigation.TenHv} \n" +
      
       $"Số lượng: " +
      
       $"{ttqg.SoluongQg} " +
       $"{ttqg.MaHvNavigation.Donvitinh}  \n" +
       
       $"Ghi chú: " +
       
       $"{ttqg.Ghichu}  \n" +
       
       $"Trạng thái: " +
       
       $"{ttqg.TrangthaiHv} \n" +
      
       $"Ngày quyên góp: " +
      
       $"{ttqg.NgayQgFormatted}\n"
      
                };

                using var client = new SmtpClient();
                client.Connect("smtp.gmail.com");
                client.Authenticate("devthai3401@gmail.com", "mfpcaknsbfmwrvzd");
                client.Send(message);
                client.Disconnect(true);
            }
            return View(ttqg);
        }

        // GET: TtQuyengopHienvats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TtQuyengopHienvats == null)

LuanVan/Views/Chiendiches/Details.cshtml
@using LuanVan.Data;
@using Microsoft.EntityFrameworkCore;
@model LuanVan.Data.Chiendich

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />

<h1>Chi tiết</h1>

<div>
    <h4>Chiến Dịch</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Tên chiến dịch:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TenCd)
        </dd>
        <dt class="col-sm-2">
            Ngày bắt đầu:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ngaybatdau)
        </dd>
        <dt class="col-sm-2">
            Ngày kết thúc:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ngayketthuc)
        </dd>
        <dt class="col-sm-2">
            Nội dung:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NoidungCd)
        </dd>
        <dt class="col-sm-2">
            Ảnh:
        </dt>
        <dd class="col-sm-10">
            <img src="@Url.Content("~/Content/images/chiendich/"+Model.AnhCd)" width="100" height="80" style="margin-left:10px; border-radius:15px; border-style:outset " />
        </dd>
        <dt class="col-sm-2">
            Nơi hỗ trợ
        </dt>
        <dd class="col-sm-10">
            @if (Model.MaNoi != null)
            {
                @Html.DisplayFor(modelItem => modelItem.MaNoiNavigation.Diachi)
                ;
            }
            else
            {
                <a>Không có</a>
            }
        </dd>
        <dt class="col-sm-2">
            Người chịu trách nhiệm
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MaTvNavigation.TenTv)
        </dd>
    </dl>
</div>
<div>
    
    <input type="button" style="width:175px" class="btn btn-secondary" value="Danh sách chiến dịch" onclick="location.href='@Url.Action("index")'" />

</div>




@if (Model.TtQuyengopHienvats.Count > 0)
{
    <hr />
    NienluancosoContext db = new NienluancosoContext();
    <h2>Thông tin quyên góp của chiến dịch</h2>
    var tong = 0;
    var tongnhan = 0;
    var tongqg = 0;


    var listChienDich = db.TtQuyengopHienvats.Include(t => t.MaCdNavigation).Include(t => t.MaHvNavigation).Include(t => t.MaTvNavigation).Include(t => t.MaMtqNavigation).Where(t => t.MaCd == Model.MaCd).ToList();
    <table class="table">
        @foreach (var item in listChienDich)
        {
            tong++;
            if (item.TrangthaiHv.Trim() == "Đã nhận" || item.TrangthaiHv.Trim() == "Đã tặng")
            {
                tongqg += (item.MaHvNavigation.Gia) * (item.SoluongQg);
                tongnhan++;
            }
        }

        <tr>
            <h4>  <b>Tổng số lượt đăng ký quyên góp của chiến dịch: @tong lượt; Đã nhận: @tongnhan lượt<br> Tổng giá trị quyên góp đã nhận:  @Html.FormatValue(tongqg, "{0:#,###}") VNĐ</b></h4>
        </tr>
        <tr>
            
            <th>
                Hiện vật
            </th>
            <th>
                Số lượng
            </th>
          

            <th>
                Ghi chú
            </th>

            <th>
                Trạng thái
            </th>
            <th>
                Ngày quyên góp
            </th>
            <th>
                Giá trị ước tính
            </th>
            <th>Người nhận</th>
        </tr>
        @foreach (var item in listChienDich)
        {



            <tr>
               
                <td>
                    @Html.DisplayFor(modelItem => item.MaHvNavigation.TenHv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoluongQg) <a>@item.MaHvNavigation?.Donvitinh</a>
                </td>
                

                <td>
                    @Html.DisplayFor(modelItem => item.Ghichu)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.TrangthaiHv)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayQg)
                </td>
                <td>
                    @(item.MaHvNavigation.Gia * item.SoluongQg) <a style="color:black">VNĐ</a>
                </td>
                @if (item.MaTvNavigation?.MaTv != null)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.MaTvNavigation.TenTv)
                    </td>
                }
                else
                {
                    <td>Chưa nhận</td>
                }
            </tr>

        }

    </table>
  
}

LuanVan/Views/Chiendiches/Index.cshtml
@model IEnumerable<LuanVan.Data.Chiendich>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .body {
        font-family: 'Roboto', sans-serif;
    }

    .box-posts {
        background: #EEE5DE;
        border: none;
        border-radius: 15px;
        box-shadow: 0px 0px 5px 5px #aaa;
        background: #f5f5f5;
        width: 100%;
        height: 350px;
        margin-bottom: 50px;
    }
   .btn{
        background-color: #2487ce;
        color:aliceblue;
   }
    .btn:hover {
        box-shadow: 0px 0px 5px 5px #789;
        background-color:aliceblue;
        color: #2487ce;
    }
    .box-posts:hover {
            box-shadow: 0px 0px 5px 5px #789;
        }
    .rowseach p {
        display: inline-block;
        margin-right: 10px;
    }
</style>
<br />
<br />
<br />

<table style="width: 1330px; font-family: 'Roboto', sans-serif;">
    <tr style="width: 100%;">
       
        <td style="width: 100%;     text-align: right;">
            <div class="container-1">
                
                    <div class="rowseach">
                        <form asp-action="index" method="get" class="form-inline">
                            <p><i class='bx bx-list-ul'></i></p>
                            <p style="font-size:30px; width:25%">

                            <select name="tt" class="form-control" asp-items="@ViewBag.tt" onchange="this.form.submit()"></select>
                              
                            </p>
                            <p><input type="text" name="SearchString" placeholder="Nhập tên chiến dịch" /></p>
                            <p>Từ: <input type="date" name="tu" /></p>
                            <p>Đến: <input type="date" name="den" /></p>

                            <p><input type="text" name="noiht" placeholder="Nhập nơi hỗ trợ" /></p>
                            <p><input type="submit" class="btn" value="Tìm kiếm" /></p>

                        </form>

                    </div>
                
            </div>
        </td>
    </tr>
</table>
@if (ViewBag.tb != null)
{
    <h3>@ViewBag.tb</h3>
}
@if (ViewBag.TuNgay != null && ViewBag.DenNgay != null)
{
    <h3>Danh sách chiến dịch từ ngày @ViewBag.TuNgay đến ngày @ViewBag.DenNgay</h3>
}
<br>
<div style="font-family: 'Roboto', sans-serif;">
    @foreach (var item in Model)
    {
        <table class="box-posts">
            <tr style="width: 100%;">


                <td style="width: 35%;">
                    <a href="@Url.Action("Details", "ChienDiches", new { id = item.MaCd })">

                        <img src="@Url.Content("~/Content/images/chiendich/"+item.AnhCd)" width="400" height="300" style="margin-left:10px; border-radius:15px; border-style:outset " />

                    </a>

                </td>
                <td style="width: 65%;">



                    <div style="height:15%">


                        <h2 style="margin-top:5px; align-content:center; margin-bottom:auto; text-align:center">
                            <a href="@Url.Action("Details", "ChienDiches", new { id = item.MaCd })">

                                @Html.DisplayFor(modelItem => item.TenCd)

                            </a>
                        </h2>
                    </div>


                    <div style="height:auto">

                        <a>@Html.DisplayFor(modelItem => item.NoidungCd)</a>

                    </div>

                    <hr>
                    <div style="height: 20%; color:#000">
                        <table>


                            <tr>


                                <td>


                                    <table>
                                        <tr>
                                            <td><i class="fas fa-barcode"></i></td>
                                            <td style="padding-left: 10px;">
                                                <b><i class='bx bx-calendar'></i> Ngày bắt đầu: </b>@Html.DisplayFor(modelItem => item.NgaybatdauFormatted)
                                            </td>
                                        </tr>


                                        <tr>


                                            <td>
                                                <i class="fas fa-calendar-alt"></i>
                                            </td>
                                            <td style="padding-left: 10px;">
                                                <b><i class='bx bx-calendar'></i> Ngày kết thúc: </b> @Html.DisplayFor(modelItem => item.NgayKetThucFormatted)
                                            </td>

                                        </tr>

                                    </table>
                                </td>

                            </tr>

                        </table>
                        <hr>

                    </div>
                    @if(item.Ngayketthuc.Date < DateTime.Now.Date)
                    {
                        <div style="height:15%; text-align:center; margin-bottom:auto; margin-top:30px ">
                            <h3 class="text-danger">Chiến dịch đã kết thúc</h3>
                        </div>
                    }else{
                    <div style="height:15%; text-align:center; margin-bottom:auto; margin-top:30px ">
                        <input type="button" class="btn" value="Quyên Góp" onclick="location.href='@Url.Action("Create", "TtQuyengopHienvats", new { id = item.MaCd })'" />
                    </div>
                    }
                </td>
            </tr>
        </table>


    }
</div>