LuanVan/Areas/Admin/Controllers/NoihotroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LuanVan.Data;
using SautinSoft.Document;

namespace LuanVan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NoihotroesController : Controller
    {
        private readonly NienluancosoContext _context;

        public NoihotroesController(NienluancosoContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> Export(int? id)
        {
            if (HttpContext.Session.GetInt32("idtv") == null)
            {
                return RedirectToAction("Login", "ThanhVien");
            }
            var count = _context.Quyens.Where(c => c.MaCn == 1 && c.MaCv == HttpContext.Session.GetInt32("cvtv")).Count();
            if (count == 0)
            {
                return RedirectToAction("norole", "Home");
            }
            if (id == null || _context.Chiendiches == null)
            {
                return NotFound();
            }

            var noihotro = await _context.Noihotros
                .Include(n => n.MaMtqNavigation)
                .Include(n => n.TtTraotangs)
                .Include(n => n.Chiendiches)
                .FirstOrDefaultAsync(n => n.Manoi == id);
            if (noihotro == null)
            {
                return NotFound();
            }

            return View(noihotro);
        }
        [HttpPost]
        public IActionResult Export(string GridHtml)
        {
            string path = Path.Combine(Directory.GetCurrentDirectory(), "HTML");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            string input = Path.Combine(path, "html1.html");
            string output = Path.Combine(path, "BaoCaoChienDich.docx");
            System.IO.File.WriteAllText(input, GridHtml);
            DocumentCore documentCore = DocumentCore.Load(input);
            documentCore.Save(output);
            byte[] bytes = System.IO.File.ReadAllBytes(output);

            Directory.Delete(path, true);

            return File(bytes, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "BaoCaoNoiHoTro.docx");
        }
        // GET: Admin/Noihotroes
        public async Task<IActionResult> Index(string? SearchString, int? tt)
        {
            if (HttpContext.Session.GetInt32("idtv") == null)
            {
                return RedirectToAction("Login", "ThanhVien");
            }
            var count = _context.Quyens.Where(c => c.MaCn == 5 && c.MaCv == HttpContext.Session.GetInt32("cvtv")).Count();
            if (count == 0)
            {
                return RedirectToAction("norole", "Home");
            }
            List<SelectListItem> items = new List<SelectListItem>
{
    new SelectListItem { Value = "1", Text = "Danh sách tất cả đề xuất" },
    new SelectListItem { Value = "2", Text = "Danh sách đề xuất chưa duyệt" },
    new SelectListItem { Value = "3", Text = "Danh sách đề xuất đã duyệt" },
     new SelectListItem { Value = "4", Text = "Danh sách đã có hỗ trợ hoặc có chiến dịch" }
};
            ViewBag.tt = new SelectList(items, "Value", "Text", tt);
            if (SearchString != null)
            {
                var nienluancosoContext2 = _context.Noihotros.Include(n => n.MaMtqNavigation).Include(n => n.TtTraotangs).Include(n => n.Chiendiches).Where(c => c.Diachi.Contains(SearchString));
                if (nienluancosoContext2.Count() == 0)
                {
                    ViewBag.tb = "Không tìm thấy đề xuất hỗ trợ có địa chỉ : " + SearchString.ToString();
                }
                else
                {
                    ViewBag.tb = "Đã tìm thấy đề xuất hỗ trợ có địa chỉ : " + SearchString.ToString();
                }
                return View(await nienluancosoContext2.ToListAsync());
            }
            if (tt == 1)
            {

                var nienluancosoContext2 = _context.Noihotros.Include(n => n.MaMtqNavigation).Include(n => n.TtTraotangs).Include(n => n.Chiendiches);

                return View(await nienluancosoContext2.ToListAsync());
            }
            if (tt == 2)
            {

                var nienluancosoContext2 = _context.Noihotros.Include(n => n.MaMtqNavigation).Include(n => n.TtTraotangs).Include(n => n.Chiendiches).Where(n => n.TrangthaiNht.Trim() == "Chưa duyệt");



                return View(await nienluancosoContext2.ToListAsync());
            }
            if (tt == 3)
            {

                var nienluancosoContext2 = _context.Noihotros.Include(n => n.MaMtqNavigation).Include(n => n.TtTraotangs).Include(n => n.Chiendiches).Where(n => n.TrangthaiNht.Trim() == "Đã duyệt");



                return View(await nienluancosoContext2.ToListAsync());
            }
            if (tt == 4)
            {

                var nienluancosoContext2 = _context.Noihotros.Include(n => n.MaMtqNavigation).Include(n => n.TtTraotangs).Include(n => n.Chiendiches).Where(n => n.Chiendiches.Count > 0 || n.TtTraotangs.Count >0);



                return View(await nienluancosoContext2.ToListAsync());
            }
            var nienluancosoContext = _context.Noihotros.Include(n => n.MaMtqNavigation).Include(n => n.TtTraotangs).Include(n => n.Chiendiches);
            return View(await nienluancosoContext.ToListAsync());
        }

        // GET: Admin/Noihotroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (HttpContext.Session.GetInt32("idtv") == null)
            {
                return RedirectToAction("Login", "ThanhVien");
            }
            var count = _context.Quyens.Where(c => c.MaCn == 5 && c.MaCv == HttpContext.Session.GetInt32("cvtv")).Count();
            if (count == 0)
            {
                return RedirectToAction("norole", "Home");
            }
            if (id == null || _context.Noihotros == null)
            {
                return NotFound();
            }

            var noihotro = await _context.Noihotros
                .Include(n => n.MaMtqNavigation)
                .Include(n => n.TtTraotangs)
                .Include(n => n.Chiendiches)
                .FirstOrDefaultAsync(n => n.Manoi == id);
            if (noihotro == null)
            {
                return NotFound();
            }

            return View(noihotro);
        }

        // GET: Admin/Noihotroes/Create
        //public IActionResult Create()
        //{
        //    if (HttpContext.Session.GetInt32("idtv") == null)
        //    {
        //        return RedirectToAction("Login", "ThanhVien");
        //    }
        //    ViewData["MaMtq"] = new SelectList(_context.Manhthuongquans, "MaMtq", "MaMtq");
            
        //    return View();
        //}

        //// POST: Admin/Noihotroes/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Manoi,MaMtq,Diachi,Tinhtrang,Canhotro,TrangthaiNht,MaTv,AnhNth")] Noihotro noihotro)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(noihotro);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["MaMtq"] = new SelectList(_context.Manhthuongquans, "MaMtq", "MaMtq", noihotro.MaMtq);
           
        //    return View(noihotro);
        //}

        // GET: Admin/Noihotroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (HttpContext.Session.GetInt32("idtv") == null)
            {
                return RedirectToAction("Login", "ThanhVien");
            }
            var count = _context.Quyens.Where(c => c.MaCn == 5 && c.MaCv == HttpContext.Session.GetInt32("cvtv")).Count();
            if (count == 0)
            {
                return RedirectToAction("norole", "Home");
            }
            if (id == null || _context.Noihotros == null)
            {
                return NotFound();
            }

            var noihotro = await _context.Noihotros.Include(n => n.MaMtqNavigation).FirstOrDefaultAsync(n => n.Manoi == id);
            if (noihotro == null)
            {
                return NotFound();
            }
            ViewData["MaMtq"] = new SelectList(_context.Manhthuongquans.Where(s => s.MaMtq == noihotro.MaMtq), "MaMtq", "HotenMtq");

            return View(noihotro);
        }

        // POST: Admin/Noihotroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Manoi,MaMtq,Diachi,Tinhtrang,Canhotro,TrangthaiNht,MaTv,AnhNth")] Noihotro noihotro)
        {
            if (id != noihotro.Manoi)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var nht = _context.Noihotros.AsNoTracking().FirstOrDefault(n => n.Manoi == id);
                    noihotro.AnhNth = nht.AnhNth;
                    _context.Update(noihotro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoihotroExists(noihotro.Manoi))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;

LuanVan/Views/Noihotroes/Create.cshtml
@model LuanVan.Data.Noihotro

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .form-group{
        width:400px;
    }
</style>
<br />
<h1>Thêm đề xuất</h1>

<h4>Nơi cần hỗ trợ</h4>
<hr />
<h2>@ViewBag.thongbao</h2>
<div  class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaMtq" class="control-label">Người đề xuất</label>
                <select asp-for="MaMtq" class ="form-control" asp-items="ViewBag.MaMtq"></select>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Diachi" class="control-label">Địa chỉ nơi cần hỗ trợ</label>
                <input asp-for="Diachi" class="form-control" />
                <span asp-validation-for="Diachi" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Tinhtrang" class="control-label">Trình trạng nơi cần hỗ trợ</label>
                <input asp-for="Tinhtrang" class="form-control" />
                <span asp-validation-for="Tinhtrang" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Canhotro" class="control-label">Cần hỗ trợ gì</label>
                <input asp-for="Canhotro" class="form-control" />
                <span asp-validation-for="Canhotro" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="AnhNth" class="control-label">Thêm hình ảnh</label>
                <input asp-for="AnhNth" type="file" id="fileImage" class="form-control-file" name="file">
                
                <br />

                <img id="preview" src="#" width="150" height="100" class="hidden" />
                <br />
                <span asp-validation-for="AnhNth" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<script>

    fileImage.onchange = evt => {

        const [file] = fileImage.files

        if (file) {

            preview.src = URL.createObjectURL(file);

            $("#preview").removeClass("hidden");

        }

    }

</script>
<div>
    <a asp-action="Index">Về danh sách</a>
</div>

LuanVan/Views/Noihotroes/Delete.cshtml
@model LuanVan.Data.Noihotro

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Xóa đề xuất</h1>

<h3>Bạn có chắc chắn muốn xóa?</h3>
<div>
    <h4>Nơi đề xuất</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Người đề xuất
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MaMtqNavigation.HotenMtq)
        </dd>
        <dt class = "col-sm-2">
            Địa chỉ
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diachi)
        </dd>
        <dt class = "col-sm-2">
           Tình trạng
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tinhtrang)
        </dd>
        <dt class = "col-sm-2">
            Cần hỗ trợ
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Canhotro)
        </dd>
        <dt class = "col-sm-2">
           Trạng thái
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrangthaiNht)
        </dd>
        <dt class = "col-sm-2">
            Hình ảnh
        </dt>
        <dd class = "col-sm-10">
            <img src="@Url.Content("~/Content/images/noihotro/"+Model.AnhNth)" width="120" height="100" style=" border-radius:15px; border-style:outset " />
        </dd>
       
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Manoi" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Về danh sách</a>
    </form>
</div>

LuanVan/Views/Noihotroes/Edit.cshtml
@model LuanVan.Data.Noihotro

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .form-group {
        width: 400px;
    }
</style>

<h1>Chỉnh sửa</h1>

<h4>Đề xuất nơi hỗ trợ</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Manoi" />
            <div class="form-group">
                <label asp-for="MaMtq" class="control-label">Người đề xuất</label>
                <select asp-for="MaMtq" class="form-control" asp-items="ViewBag.MaMtq"></select>
                <span asp-validation-for="MaMtq" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Diachi" class="control-label">Địa chỉ</label>
                <input asp-for="Diachi" class="form-control" />
                <span asp-validation-for="Diachi" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Tinhtrang" class="control-label">Tình trạng</label>
                <input asp-for="Tinhtrang" class="form-control" />
                <span asp-validation-for="Tinhtrang" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="Canhotro" class="control-label">Cần hỗ trợ</label>
                <input asp-for="Canhotro" class="form-control" />
                <span asp-validation-for="Canhotro" class="text-danger"></span>
            </div><br />
           
            <div class="form-group">
                <label asp-for="AnhNth" class="control-label">Thêm hình ảnh</label>
                <input asp-for="AnhNth" type="file" id="fileImage" class="form-control-file" name="file">

                <br />

                <img id="preview" src="#" width="150" height="100" class="hidden" />
                <br />
                <span asp-validation-for="AnhNth" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<script>
    preview.src = "@Url.Content("~/Content/images/noihotro/"+Model.AnhNth)";
    fileImage.onchange = evt => {

        const [file] = fileImage.files

        if (file) {

            preview.src = URL.createObjectURL(file);

            $("#preview").removeClass("hidden");

        }

    }


</script>
<div>
    <a asp-action="Index">Về danh sách</a>
</div>

LuanVan/Views/Noihotroes/Index.cshtml
@model X.PagedList.IPagedList<LuanVan.Data.Noihotro>
@using X.PagedList.Mvc.Core
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />

<style>
    h1 {
        font-family: Arial, sans-serif;
        font-size: 29px;
        text-align: center;
    }

    /* Thiết lập màu nền và khoảng cách cho thẻ p */
    p {
        background-color: #f2f2f2;
        padding: 10px;
    }

    /* Thiết lập kiểu cho bảng */
    .table {
        border-collapse: collapse;
        width: 1330px;
        text-align: center;
        color: #6c757d;
        background-color: #f1f3f5;
    }

        /* Thiết lập màu nền và kiểu cho tiêu đề bảng */
        .table thead {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        /* Thiết lập màu nền và kiểu cho từng hàng trong bảng */
        .table tr {
            background-color: #ffffff;
        }

    .table-heading {
        text-align: center;
    }
    /* Thiết lập kiểu cho các ô trong bảng */
    .table td, .table th {
        border: 1px solid #dddddd;
        text-align: center;
        padding: 8px;
    }

    /* Thiết lập kiểu cho các liên kết */
    a {
        color: #337ab7;
        text-decoration: none;
    }

        /* Thiết lập kiểu cho liên kết khi rê chuột vào */
        a:hover {
            text-decoration: underline;
        }

    .btn {
        align-items: center;
        margin: 5px;
    }

    .rowseach p {
        display: inline-block;
        margin-right: 10px;
    }

    
    .pagination-container li {
        font-size: 25px;
        margin-left: 10px;
        margin-right: 10px;
        
    }
    
</style>
<h1>Danh Sách Đề Xuất Hỗ Trợ</h1>
<br />
@using (Html.BeginForm())
{
    <div class="rowseach">
        <p>
            <input type="button" style="width:120px;" class="btn btn-success" value="Thêm đề xuất" onclick="location.href='@Url.Action("Create")'" />
        </p>
        <form asp-action="index" method="get" class="form-inline">
            @if(Context.Session.GetInt32("idmtq") != null)
            {
                <p> <select name="tt" class="form-control" asp-items="@ViewBag.tt" onchange="this.form.submit()"></select></p>
            }
          
            <p><input type="text" name="SearchString" placeholder="Nhập địa chỉ" /></p>


            <p><input type="submit" class="btn btn-primary" value="Tìm kiếm" /></p>

        </form>

    </div>
}

@if (ViewBag.tb != null)
{
    <p style="font-size:20px"><b>@ViewBag.tb</b></p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                Địa chỉ
            </th>
            <th>
                Tình trạng
            </th>
            <th>
                Cần hỗ trợ
            </th>
            <th>
                Hình ảnh
            </th>
            <th>
                Trạng thái
            </th>
            <th>
                Người đề xuất
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Diachi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tinhtrang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Canhotro)
                </td>
                <td>
                    <img src="@Url.Content("~/Content/images/noihotro/"+item.AnhNth)" width="120" height="100" style=" border-radius:15px; border-style:outset " />
                </td>
                <td>
                    @if (item.TtTraotangs.Count > 0 && item.Chiendiches.Count > 0)
                    {
                        <span>Đã mở chiến dịch và trao tặng</span>
                    }
                    else if (item.Chiendiches.Count > 0)
                    {
                        <span>Đã mở chiến dịch</span>
                    }
                    else if (item.TtTraotangs.Count > 0)
                    {
                        <span>Đã có hỗ trợ</span>


                    }
                    else
                    {
                        <span>@Html.DisplayFor(modelItem => item.TrangthaiNht)</span>
                    }

                </td>

                <td>
                    
                       @Html.DisplayFor(modelItem => item.MaMtqNavigation.HotenMtq)

                </td>

               

                    @if (item.MaMtqNavigation.MaMtq == Context.Session.GetInt32("idmtq") && item.TrangthaiNht.Trim() == "Chưa duyệt" && item.TtTraotangs.Count == 0 && item.Chiendiches.Count ==0)
                    {
                    <td align="right" width="100px">
                        <input type="button" style="width:90px" class="btn btn-secondary" value="Chi tiết" onclick="location.href='@Url.Action("Details", new { id = item.Manoi })'" />
                        <input type="button" style="width:90px;" class="btn btn-primary" value="Sửa" onclick="location.href='@Url.Action("Edit", new { id = item.Manoi })'" />
                        <input type="button" style="width:90px" class="btn btn-danger" value="Xóa" onclick="location.href='@Url.Action("Delete", new { id = item.Manoi })'" />
                    </td>
                    }
                    else if (item.MaMtqNavigation.MaMtq == Context.Session.GetInt32("idmtq") &&  item.TrangthaiNht.Trim() == "Đã duyệt" && item.TtTraotangs.Count == 0 && item.Chiendiches.Count == 0)
                    {
                         <td align ="right" width="100px">
                        <input type="button" style="width:90px" class="btn btn-secondary" value="Chi tiết" onclick="location.href='@Url.Action("Details", new { id = item.Manoi })'" />
                       
                        <input type="button" style="width:90px" class="btn btn-danger" value="Xóa" onclick="location.href='@Url.Action("Delete", new { id = item.Manoi })'" />
                    </td>
                    }
                    else if(Context.Session.GetInt32("idmtq") != null)
                    {
                         <td align ="right" width="100px">
                        <input type="button" style="width:90px" class="btn btn-secondary" value="Chi tiết" onclick="location.href='@Url.Action("Details", new { id = item.Manoi })'" />
                    </td>
                    }
                   
            </tr>
        }    
    </tbody>
</table>
<div>
    @Html.PagedListPager(Model,page=>Url.Action("index","Noihotroes", new{page = page}))
</div>